brewery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('tourbooking.urls'), name='tourbooking.urls'),
    path('accounts/', include('allauth.urls')),
]

tourbooking/urls.py
from django.urls import path
from tourbooking import views

urlpatterns = [
    path('', views.EventList.as_view(), name='index'),
    path('<slug:slug>/', views.EventDetail.as_view(), name='event-detail'),
]

tourbooking/models.py
from django.db import models
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))


class Event(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique=True)
    featured_image = CloudinaryField('image', default='placeholder')
    description = models.TextField()
    created_on = models.DateTimeField(auto_now=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    status = models.IntegerField(choices=STATUS, default=0)
    
    class Meta:
        ordering = ['-created_on']
        
    def __str__(self):
        return self.title
    
    
class Booked(models.Model):
    booking = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="booked")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    approved = models.BooleanField(default=False)

    def __str__(self):
        return f"Booked {self.body} by {self.name}"

tourbooking/forms.py
from .models import Booked
from django import forms


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booked
        fields = ('body',)

tourbooking/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic, View
from .models import Event
from .forms import BookingForm



class EventList(generic.ListView):
    model = Event
    queryset = Event.objects.filter(status=1).order_by("-created_on")
    template_name = 'index.html'
    paginate_by = 6


class EventDetail(View):
    
    def get(self, request, slug, *args, **kwargs):
        queryset = Event.objects.filter(status=1)
        event = get_object_or_404(queryset, slug=slug)
        booking = event.booked.filter(approved=True)
        
        booking_form = BookingForm(data=request.POST)
        if booking_form.is_valid():
            booking_form.instance.email = request.user.email
            booking_form.instance.name = request.user.username
            booking = booking_form.save(commit=False)
            booking.post = event
            booking.save()
        else:
            booking_form = BookingForm()
        
        return render(
            request,
            'event-detail.html',
            {
                'event': event,
                'booking': booking,
                'booked': True,
                'bookingform': BookingForm()
            },
        )
          
    def event(self, request, slug, *args, **kwargs):
        queryset = Event.objects.filter.order_by('-created_on')
        event = get_object_or_404(queryset, slug=slug)
        
        return render(
            request,
            'event-detail.html',
            {
                'event': event
            },
        )

    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <title>Rimbo Beer Brewery</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}"><img class="logo-image" src='https://github.com/ejkington/rimbo-beer-brewery-ms1/blob/master/assets/images/Rimbo-logo.png?raw=true'></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg"
                role="alert">
                {{ message | safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-lable="Close">
                </button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% block event %}       

    {% endblock event %}
    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>
    <!--Footer and social media links-->
    <footer id="footer">
        <ul class="social-networks">
            <li>
                <a href="https://facebook.com" target="_blank" rel="noopener" aria-label="Visits our facebook page (opens in a new tab)"><i class="fab fa-facebook"></i></a>
            </li>
            <li>
                <a href="https://twitter.com" target="_blank" rel="noopener" aria-label="Visits our twitter page page (opens in a new tab)"><i class="fab fa-twitter-square"></i></a>
            </li>
            <li>
                <a href="https://youtube.com" target="_blank" rel="noopener" aria-label="Visits our youtube page (opens in a new tab)"><i class="fab fa-youtube"></i></a>
            </li>
            <li>
                <a href="https://instagram.com" target="_blank" rel="noopener" aria-label="Visits our instagram page (opens in a new tab)"><i class="fab fa-instagram"></i></a>
            </li>
            <li>
                <h3>©<br>Niklas Färeborg</h3>
            </li>
        </ul>
    </footer>
    <script>
        setTimeout(function() {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 3000);
    </script>
    <!-- font awesome-->
<script src="https://kit.fontawesome.com/aecfa50529.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>

</html>

templates/event-detail.html
{% extends 'base.html' %}
{% block content %}


<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">{{ event.title }}</h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="post-subtitle">{{ event.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in post.featured_image.url %}
                <img src="https://media.istockphoto.com/photos/hispanic-female-craft-brewer-examining-beer-sample-picture-id1197894094" width="100%">
                {% else %}
                <img src=" {{ post.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The post content goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <p class="card-text ">
                    {{ event.description | safe }}
                </p>
               {% if user.is_authenticated %}
                <section class="form-section">
                    <form method="POST" action="https://formdump.codeinstitute.net/" class="signup-form">
                        <h2>Book Tour</h2>
                        <label for="fname">First Name</label>
                        <input id="fname" name="first_name" type="text" class="text-input" required>
            
                        <label for="lname">Last Name</label>
                        <input id="lname" name="last_name" type="text" class="text-input" required>
            
                        <label for="email">Email Address</label>
                        <input type="email" id="email" name="email_address" class="text-input" required>
                        
                        <label for="guests">Guests</label>
                        <input type="number" id="guest" name="guest" class="number-input" min="1" max="10" required>

                        <input class="join-button" type="submit" value="Beer me up!">
                    </form>
                </section>
                {% endif %}

               </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
    </div>
</div>

{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block content %}
<h3 class="event-text"> Hello and welcome to</h3>
<h3 class="event-text"> Rimbo Beer Brewery Events </h3>
<p class="event-text"> Please check out our events and if you wish to book an event please register or login above.</p>
<div class="container-fluid">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for event in event_list %}
                <div class="col-md-4">
                    <div class="card-mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if 'placeholder' in event.featured_image.url %}
                                <img class="card-img-top"
                                    src="https://media.istockphoto.com/photos/hispanic-female-craft-brewer-examining-beer-sample-picture-id1197894094">
                                {% else %}
                                <img class="card-img-top" src=" {{ event.featured_image.url }}">
                                {% endif %}
                            </div>
                            <a href="{% url 'event-detail' event.slug  %}" class="post-link">
                                <h2 class="card-title">{{ event.title }}</h2>
                            </a>
                            <hr />
                            <p class="card-text text-muted h5">{{ event.created_on }}
                                
                            </p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:4 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{%endblock%}